name: fader_with_buttons
description: Showing the use of the Fader with buttons

version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fader:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
