include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    omit_local_variable_types: false
    avoid_types_on_closure_parameters: false
    use_setters_to_change_properties: false
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - '**/*_test.dart'
