name: flutter_fader
description: A flutter widget that allows you to fade a child widget in and out. When faded out the child widget is removed from the tree (it can't be interacted with)
version: 2.0.1
repository: https://github.com/TNorbury/flutter-fader
homepage: https://github.com/TNorbury/flutter-fader
issue_tracker: https://github.com/TNorbury/flutter-fader/issues

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter

flutter:
